name: CVG Custom Plugin
main: com.centralviewgaming.mccustomplugin.CVGCustomPlugin
version: 1.0
commands:
    cvg:
        description: CentralView Gaming Custom Plugin
        usage: |
                Usage:
                /cvg vanish <player>
                /cvg show <player>
